force-app/main/default/objects/Invalid_Request__c/Invalid_Request__c.object-meta.xml
<CustomObject>
    <label>Invalid Request</label>
    <nameField>
        <label>Invalid Requests Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invalid Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invalid_Request__c/fields/Lead_Record__c.field-meta.xml
<CustomField>
    <fullName>Lead_Record__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead Record</label>
    <referenceTo>Lead_Record__c</referenceTo>
    <relationshipLabel>Invalid Requests</relationshipLabel>
    <relationshipName>Invalid_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Record__c/Lead_Record__c.object-meta.xml
<CustomObject>
    <label>Lead Record</label>
    <nameField>
        <label>Lead Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Record__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountHandler.cls
public with sharing class AccountHandler {    
    public AccountHandler() {
    }
    public static void loadAccounts(){
        String[] countries = new String[] {'USA United States','CAN Canada'};
        List<Account> accs = getAccounts(countries);
        if (accs.size() == 0) {
            for (String country : countries) {
                Account acc = new Account();
                acc.Name = country;
                acc.Country__c = country;
                accs.add(acc);
            }
            insert accs;
        }    
    }
    public static void checkAccounts(){
        String[] countries = new String[] {'USA United States','CAN Canada'};
        List<Account> accs = getAccounts(countries);
        if (accs.size() > 0) {
            delete [SELECT Id FROM Lead_Record__c];
            delete [SELECT Id FROM Invalid_Request__c];
            delete [SELECT Id FROM Opportunity];            
            delete [SELECT Id FROM Contact]; 
            delete [SELECT Id FROM Account];            
        }    
    }    
    public static List<Account>  getAccounts(String[] pCountries){
        return [SELECT Id, Name, Country__c FROM Account WHERE Country__c IN : pCountries AND Name IN : pCountries LIMIT 2];
    } 
    public static Account[]  getAccount(String pCountry){
        loadAccounts();
        return getAccounts(new String[]{  pCountry });
    } 
}